MESSAGES = [
    "Get yo money up, not yo IG reel count up",
    "Back to work unc, time is ticking",
    "Bro is cooking absolutely NOTHING rn 💀",
    "Imagine fumbling the bag this hard",
    "Locked out? Nah, LOCK IN.",
    "Skill issue detected.",
    "Caught you lacking in 4K 📸",
    "This is why you're not the main character.",
    "Doomscrolling is crazy behavior.",
    "Erm, what the sigma? Get back to work.",
    "You're not that guy pal, trust me. Work.",
    "Academic weapon status: REVOKED.",
    "Stop mewing and start doing.",
    "L mans behavior.",
    "Not very demure, not very mindful of you.",
    "I know you ain't watching Brainrot rn.",
    "It's giving unemployed energy.",
    "Wanna be a boss? Then stop taking Ls.",
    "Focus or get mogged by life.",
    "You fell off + ratio + get back to work.",
    "Bro is allergic to productivity.",
    "Bombastic side eye... 👀",
    "Is this your academic comeback? Didn't think so.",
    "Standing on business? More like sitting on TikTok.",
    "We not making it out the hood with this work ethic.",
    "Chat, is this real? You distracted again?",
    "NPC behavior detected. Wake up.",
    "Go touch keyboard (not grass).",
    "Your attention span is cooked.",
    "Don't let the intrusive thoughts win.",
    "Delulu is not the solulu. Do the work.",
    "I fear you are not locked in.",
    "Zero aura points for this distraction.",
    "Stop yapping and start typing.",
    "Brainrot levels critical. Abort.",
    "Are you winning son? No. You are not.",
    "Only Ohio rizzlers get distracted this much.",
    "Skibidi toilet has more focus than you.",
    "You have one job. ONE JOB.",
    "Trying to be a sigma? This ain't it.",
    "Grimace shake energy rn.",
    "Stop simping for distractions.",
    "Hold this L and get back to code.",
    "Bro thinks he's him (he's distracted).",
    "Can't park there mate. Back to work.",
    "Who let bro cook? Turn the stove off.",
    "Call an ambulance... but not for me (for your grades).",
    "Emotional damage? Nah, career damage.",
    "Rent is due. Act like it.",
    "Fatherless behavior (the distraction, not you).",
    "Glazing the internet won't pay the bills.",
    "Stop being mid.",
    "I'm in your walls. Work.",
    "Bet you won't close that tab.",
    "No cap, you're slacking.",
    "Sheesh! Look at that empty document.",
    "Yeet the phone.",
    "Leaving you on read until you finish this.",
    "Vibe check: FAILED."
]